# Generated by Django 5.0.1 on 2024-02-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'nebulas'), ('ESTRELA', 'estrela'), ('GALÁXIA', 'galáxia'), ('PLANETA', 'planeta')], default='', max_length=100),
        ),
    ]
