# Generated by Django 5.0.1 on 2024-02-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosas'), ('ESTRELA', 'Estrelas'), ('GALÁXIA', 'Galáxias'), ('PLANETA', 'Planetas')], default='', max_length=100),
        ),
    ]
